<?php

namespace Tests\Feature\Dashboard;

use App\Models\Admin;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class DashboardHomePageTest extends TestCase
{
    use RefreshDatabase;

    private Admin $admin;
    private User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->admin = Admin::factory()->create();
        $this->user = User::factory()->create();
    }

    public function test_if_redirect_to_login_if_not_authenticated()
    {
        $this->get('/dashboard')
            ->assertStatus(302)
            ->assertRedirectToRoute('dashboard.login');
    }

    public function test_if_redirect_to_dashboard_if_authenticated()
    {
        $this->actingAs($this->admin, 'admin')
            ->get('/dashboard')
            ->assertStatus(200);
    }

}
